services:
  mysql:
    image: mysql:9.7.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - janicerules:/var/lib/mysql
    networks:
      - bridgenet1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmysecretpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  flaskapp1:
    image: janicengugi/flask-mysql-time:${APP1_IMAGE_TAG:-latest}
    container_name: flask-app-1
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      SERVER_PORT: 8001
      INSTANCE_NAME: flask-app-1
    ports:
      - "8001:8001"
    networks:
      - bridgenet1

  flaskapp2:
    image: janicengugi/flask-mysql-time:${APP2_IMAGE_TAG:-latest}
    container_name: flask-app-2
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      SERVER_PORT: 8002
      INSTANCE_NAME: flask-app-2
    ports:
      - "8002:8002"
    networks:
      - bridgenet1

volumes:
  janicerules:
    external: true

networks:
  bridgenet1:
    external: true

